name: Push to ADO Repo

on:
  push:
    branches:
      - master  # Change to the branch you want to trigger this action on

jobs:
  sync_ado:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the full history to avoid shallow clone issues

    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Add Azure DevOps remote repository
      run: |
        git remote add azure https://mullamuris:${{ secrets.ADO_TOKEN }}@dev.azure.com/mullamuris/POC/_git/POC
        git fetch azure

    - name: Force reset Azure DevOps branch to match GitHub
      run: |
        git reset --hard origin/master
        git push --force azure master
